services:
  - type: web
    name: my-web-api
    runtime: docker
    repo: https://github.com/KSaiVishnu/TimeSnapBackend
    region: oregon
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: AZURE_SQL
        value: "true"
      - key: AZURE_SQL_CONNECTION_STRING
        value: "Server=tcp:timesnap-server.database.windows.net,1433;Database=ProjectDb;Authentication=Active Directory Default"
    plan: free
